# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField()),
                ('state', models.IntegerField(choices=[(0, 'Unbekannt'), (1, 'Kommt sicher'), (2, 'Kommt nicht'), (3, 'Kommt vermutlich'), (4, 'Unentschlossen')], default=0)),
            ],
        ),
    ]
