# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teilnehmer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
