# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160423_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unbekannt'), (1, 'Kommt sicher'), (2, 'Kommt nicht'), (3, 'Kommt vermutlich'), (4, 'Unentschlossen')], default=0, verbose_name='Kommt'),
        ),
    ]
