# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160426_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Ist Lehrer'),
        ),
    ]
