# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160428_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teilnehmer',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='teilnehmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teilnehmer'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='intern_comment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
    ]
