# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teilnehmer',
            name='is_teacher',
        ),
    ]
