# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_teilnehmer_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=list,
                help_text='Durch ein Komma getrennt',
                size=None, verbose_name='hobbies'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='image_new',
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to='teilnehmer',
                verbose_name='Aktuelles Bild'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='image_old',
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to='teilnehmer',
                verbose_name='Erstes klassenbild'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='job',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beruf/Beschäftigung'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='kids',
            field=models.PositiveIntegerField(default=0, verbose_name='Anzahl Kinder'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='location_current',
            field=models.CharField(blank=True, max_length=255, verbose_name='Wohnort'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='locations_old',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text='Durch ein Komma getrennt',
                size=None,
                verbose_name='Wohnorte seit der Schulzeit'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='mail_public',
            field=models.BooleanField(
                default=True,
                help_text='Die Adresse wird nur Klassenintern veröffentlicht.',
                verbose_name='E-Mail Adresse darf veröffentlicht werden'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='relationship_status',
            field=models.CharField(default='Zu haben', max_length=32, verbose_name='Beziehungsstatus'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='school_memory',
            field=models.TextField(
                blank=True,
                help_text='Eine besondere Erinnerung an die gemeinsame Schulzeit.',
                verbose_name='Erinnerung an Schulzeit'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='token',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='state',
            field=models.IntegerField(
                choices=[(0, 'Unbekannt'), (1, 'Kommt sicher'), (2, 'Kommt nicht'), (3, 'Kommt vermutlich'), (4, 'Unentschlossen')],
                default=0,
                help_text='Wird am Klassentreffen dabei sein.',
                verbose_name='Ist dabei'),
        ),
    ]
