# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160526_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnehmer',
            name='image_new',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='teilnehmer', verbose_name='Aktuelles Bild'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='image_old',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='teilnehmer', verbose_name='Erstes klassenbild'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='locations_old',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Wohnorte seit der Schulzeit'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unbekannt'), (1, 'Kommt sicher'), (2, 'Kommt nicht'), (3, 'Kommt vermutlich'), (4, 'Unentschlossen')], default=0, help_text='Wird am Klassentreffen dabei sein.', verbose_name='Ist dabei'),
        ),
    ]
