# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:11
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160526_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnehmer',
            name='image_new',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='teilnehmer', verbose_name='Aktuelles Bild'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='image_old',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='teilnehmer', verbose_name='Erstes klassenbild'),
        ),
    ]
